spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Manishi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=my-super-secret-key-for-development-only-123456789
jwt.expiration=86400000

# Google OAuth2 Settings
google.client-id=your-google-client-id.apps.googleusercontent.com

# Cloudinary Credentials
cloudinary.cloud-name=dauo5j35d
cloudinary.api-key=316919281577482
cloudinary.api-secret=h7BY4YSySmYrNh2cPsfwuSxg6-Y
