-- PostgreSQL Schema Migration: Add iCarry Shipping API columns to orders table

ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipment_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS awb_number VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier_name VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipment_status VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_charge DECIMAL(19, 2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS estimated_delivery_date TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS label_url VARCHAR(1000);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pickup_requested BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pickup_date TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS reverse_shipment_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_attempts INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS last_tracking_sync TIMESTAMP;
